version = 1
SPDX-PackageName = "KDAB Boat Demo"
SPDX-PackageSupplier = "<info@kdab.com>"
SPDX-PackageDownloadLocation = "https://www.github.com/KDAB/KDBoatDemo"

[[annotations]]
path = "**.qrc"
precedence = "aggregate"
SPDX-FileCopyrightText = "2013-2021 Klarälvdalens Datakonsult AB, a KDAB Group company <info@kdab.com>"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = ["resources/images/**", "**.svg"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2013-2021 Klarälvdalens Datakonsult AB, a KDAB Group company <info@kdab.com>"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "resources/albumcover/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2021 Klarälvdalens Datakonsult AB, a KDAB Group company <info@kdab.com>"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = ["resources/fonts/Lato**", "resources/fonts/OpenSans**"]
precedence = "aggregate"
SPDX-FileCopyrightText = "google"
SPDX-License-Identifier = "OFL-1.1 OR Apache-2.0"
